### ISSUE TITLE
Error thrown when calling wpdbd_general_page_settings in class-admin.php

### ISSUE THREAD

**Issue by MattGeri** [wpdiscussionboard/wp-discussion-board#50]
**Describe the bug**
On some environments a Php error is being thrown when the `wpdbd_general_page_settings()` function is called in `class-admin.php` because it's not being called from the global namespace like: `\wpdbd_general_page_settings()`

**Steps to Reproduce**
See: https://wpdiscussionboard.com/discussion-topics/wp-cron-fatal-error/

**Expected behavior**
An error should not be thrown when the settings function is called

**Environment information**
WordPress version 5.8.1
Current theme: Yas Elementor (version )
Current plugin: Discussion Board (version 2.4.2)
PHP version 7.4.24

**Comment by contactashish13** [comment]
@MattGeri a point to note: this seems to be triggered by the plugin `https://wpmudev.com/updates/` and on a WP Engine environment. I cannot reproduce it at my end.

Theoretically, this should not happen because [this code](https://github.com/wpdiscussionboard/wp-discussion-board/blob/master/includes/classes/admin/class-admin.php#L28) is called in the WP admin just like [this code](https://github.com/wpdiscussionboard/wp-discussion-board/blob/master/wp-discussion-board.php#L28-L30) is. Maybe this is happening because the plugin is simulating admin `WPMUDEV_Dashboard_Utils->simulate_admin_actions(”)` and not completely?

**Comment by MattGeri** [comment]
Fixed in #48
